### ISSUE TITLE
UI page is not visible, It's keep loading.

### ISSUE THREAD

**Issue by Sriramraja05** [MedTAG/medtag-core#1]
Hi, Thanks,
I am trying to install the MedTAG codebase in my system, After installation, Once I logged in I am not able to see any UI, It keeps loading.
Any Idea about the issue?

![Screenshot 2022-03-07 203109](https://user-images.githubusercontent.com/76657085/157059595-6630a3cb-7a74-49d6-95f0-cc6290cb168f.png)

**Comment by giachell** [comment]
Hi,

Thank you for pointing this out, we should have just fixed the bug you experienced.

Please, clone the repository again, redo the whole installation process and run MedTAG in "Test Mode".  Note that you need to remove first any previous data concerning the project, including the related docker images. 

Please, let us know if you experience any other issues, we are glad to help you.

Thank you again for your feedback.

**Comment by Sriramraja05** [comment]
Hi, Thanks for your response,
I cloned the repository and cleared the previous data and docker image, Installed again in test mode only, Still, I am facing the same error.

Thanks again. Can you please guide me?

**Comment by giachell** [comment]
Hi, sure,

First of all, did you remove your browser cache? If no, please clean your browser cache and reload the page at the following URL: http://0.0.0.0:8000/login.

Secondly, could you please provide further information about the issue and your current environment? For instance, what is your OS?

Thank you again for your feedback and patience.

**Comment by Sriramraja05** [comment]
Hi sure,
Thanks, I cleared the cache and checked again the issue remains the same, 

Of course, I am trying in Ubuntu 20.2 let's ,VM on GCP, 
Initially, I created a centos medtag docker image, After I tied the ubuntu image. Both get the same error.

Also, I see the warning as Postgres API key is not set, I generated API key from NCIM account and exports inside the docker container but same error.

**Comment by giachell** [comment]
Hi,

Thank you for your feedback, I think the issue you are facing concerns the front-end and not the back-end. 

Could you please provide a screenshot of the "Network" tab of the developer tools of your browser? So I can check the HTTP requests done.

Thank you for your kind collaboration and patience.

**Comment by Sriramraja05** [comment]
Hi,
Thank you so much, I am sorry for the late response,

Below are the screenshot for network and console screenshots,
![consoleScreenShot](https://user-images.githubusercontent.com/76657085/166627966-f66a1f2c-257b-4b8e-9c98-4b8f16cdee0d.png)
![networkScreenShot](https://user-images.githubusercontent.com/76657085/166627974-d4709103-9990-4f29-9d15-4396e455f6f6.png)

![Screenshot 2022-05-04 111311](https://user-images.githubusercontent.com/76657085/166628328-05bdc954-a86d-4c2a-913b-685637fec0fa.png)

**Comment by praveenk0007** [comment]
> @giachell @OrnellaIrrera  Is there any resolution to this issue .Thanks.

**Comment by giachell** [comment]
Hi,

We should have fixed the issue. Please, download the new release of MedTAG (v1.0.6) and check out the new point five of the installation procedure here:  https://github.com/MedTAG/medtag-core#installation.
